# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Trip'n Touille
email: contact@tripntouille.com
description: "Escapade en cuisine avec les habitants du monde : des recettes grapillées en infiltrant les cuisines, des rencontres époustouflantes épiçant les plats et des bonnes adresses relevant le voyage. Le tout avec notre regard curieux sur le monde."
baseurl: "" # the subpath of your site, e.g. /blog
welcome: "/blog"
url: "https://www.tripntouille.com/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username:
# github_username:
permalink: /:categories/:year/:month/:day/:title/
excerpt_separator: <!--fin extrait-->
mapbox_token: "pk.eyJ1IjoiZnJhbmNvaXMybWV0eiIsImEiOiJjam92dHo3ZzAwbGN4M3VvZHR0NWhoZmJkIn0.VEQcpAFfNceyDQiBkH9MJw"

image: /img/default-image.png

# settings for SEO tag
author: "Julie Plozner & Sylvain Gournay"
logo: /favicon.ico
lang: fr_FR

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-auto-image
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 5
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - scripts/
  - .travis.xml
  - config
  - .git/
  - .idea/

jekyll-archives:
  enabled:
    - tags
    - categories
  layouts:
    tag: list-posts-with-map
    category: list-posts
  permalinks:
    tag: '/voyages/:name/'
    category: '/recettes/:name'

algolia:
  application_id: WMZ445EG6N
  index_name: prod_tripntouille
  searchKey: ec4a358a9ec50f1154907b40bd58ab9a
  files_to_exclude:
    - recettes-*/**

collections:
  posts:
    output: true
    permalink: /voyages/:year/:month/:day/:title/
  recipes:
    output: true
    permalink: /recettes/:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
